### ISSUE TITLE
I Want to add my own files, and a auto-run feature

### ISSUE THREAD

**Issue by xTGuy** [arch-installer/setup#2]
Hey, i was wondering how i could add my own files, because i was making my new project called "SwayyOS". The point of it is to make linux easier. And to do that, i need to add my own scripts, so i was wondering if you can add a feature to add your own files to a desired directory and a feature to auto-run a script on startup of the installed OS.

**Comment by JamiKettunen** [comment]
Use this as a learning opportunity to do that yourself, that's what all of this was for me over 4 years ago now. I'll now go ahead and archive everything here.
